-- MySQL Script generated by MySQL Workbench
-- 10/19/18 16:44:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema videogames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(64) NOT NULL COMMENT "Le pseudo de l'utilisateur",
  `email` VARCHAR(64) NOT NULL COMMENT "L'email de l'utilisateur",
  `password` VARCHAR(64) NOT NULL COMMENT "Le mot de passe de l'utilisateur",
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création du type',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour du type',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardware`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hardware` ;

CREATE TABLE IF NOT EXISTS `hardware` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom de la console',
  `constructor` VARCHAR(64) NOT NULL COMMENT 'Le constructeur de la console',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création de la console',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour de la console',
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hardware_user_idx` (`user_id` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `videogames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videogames` ;

CREATE TABLE IF NOT EXISTS `videogames` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom du jeu',
  `editor` VARCHAR(64) NOT NULL COMMENT "L'editeur du jeu",
  `developer` VARCHAR(64) NOT NULL COMMENT "Le developer du jeu",
  `release` DATE NOT NULL COMMENT "L'année de sortie du jeu",
  `finished` TINYINT NOT NULL DEFAULT 1 COMMENT "Savoir si le jeu est terminé ou non"
  `picture` VARCHAR(128) NULL COMMENT "L'image du jeu",
  `description` TEXT NULL COMMENT "La description du jeu",
  `box` TINYINT NOT NULL DEFAULT 1 COMMENT "Savoir si la boite du jeu est présente"
  `manual` TINYINT NOT NULL DEFAULT 1 COMMENT "Savoir si la notice du jeu est présente"
  `physical` TINYINT NOT NULL DEFAULT 1 COMMENT "Savoir si le jeu est en physique"
  `demat` TINYINT NOT NULL DEFAULT 1 COMMENT "Savoir si le jeu est en dématérialisé"
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création du jeu',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour du jeu',
  `user_id` INT UNSIGNED NOT NULL,
  `hardware_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videogames_user_idx` (`user_id` ASC)
  INDEX `fk_videogames_hardware_idx` (`hardware_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
